name: dart_pad
description: DartPad Local

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  test: ^1.17.12
  mocktail: ^0.2.0
  mockito: ^5.0.17
  build_runner: ^2.1.7


flutter:

  uses-material-design: true